# Generated by Django 2.1.1 on 2018-09-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietor', '0002_remove_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
