# Generated by Django 2.1.1 on 2018-09-28 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proprietor', '0003_auto_20180928_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('T', 'Tenant'), ('O', 'Owner')], default='O', max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('phone_number', models.CharField(max_length=12)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprietor.Property')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
