# Generated by Django 2.1.1 on 2018-09-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietor', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='addresss',
            new_name='address',
        ),
    ]
