# Generated by Django 2.1.1 on 2018-09-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietor', '0009_auto_20180930_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
