# Generated by Django 2.1.1 on 2018-10-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietor', '0013_tenant_rent_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='user',
            new_name='owner',
        ),
    ]
