# Generated by Django 2.1.1 on 2018-10-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proprietor', '0014_auto_20181009_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='user',
            new_name='tenant',
        ),
    ]
