# Generated by Django 2.1.1 on 2018-10-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietor', '0016_auto_20181010_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
